{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.photo_manager",
    "module": "photo_manager_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_debug-1.0.aar",
          "url": "photo_manager_debug-1.0.aar",
          "size": 201462,
          "sha512": "6d74995c7dfe77533f591c1dff635571ce8b47b8ee6b52960715c98cce986cf03275f58665ce70111526f101899e5c29dc14805d78191860d3a5f03bda2e7988",
          "sha256": "d72bf996aab1caac9dff7356103d74c55afcd27b5972c2174a256c09ac3c6862",
          "sha1": "13ec9152994a4021ca863439bfd1185ba4cd2748",
          "md5": "e9816323a0f21309466ef05d81a039d8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_debug-1.0.aar",
          "url": "photo_manager_debug-1.0.aar",
          "size": 201462,
          "sha512": "6d74995c7dfe77533f591c1dff635571ce8b47b8ee6b52960715c98cce986cf03275f58665ce70111526f101899e5c29dc14805d78191860d3a5f03bda2e7988",
          "sha256": "d72bf996aab1caac9dff7356103d74c55afcd27b5972c2174a256c09ac3c6862",
          "sha1": "13ec9152994a4021ca863439bfd1185ba4cd2748",
          "md5": "e9816323a0f21309466ef05d81a039d8"
        }
      ]
    }
  ]
}
