{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9519,
          "sha512": "24c66641025742496274449d9c708c7f778243718e13625032705eb86f1bc52c66a4db09818e75abaccff52ccee5b9d3eaa9bf12ef1bb9e0a3ce05a3bd915708",
          "sha256": "c020aa3f4ea0cce204dd633a70cad7cb745178bb08634dce0cb5c5fc05c255a6",
          "sha1": "965719663fd80fb683a062882c3d869bb8b99d2c",
          "md5": "35bcf21a1fcef4eda9904e95e1bca048"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9519,
          "sha512": "24c66641025742496274449d9c708c7f778243718e13625032705eb86f1bc52c66a4db09818e75abaccff52ccee5b9d3eaa9bf12ef1bb9e0a3ce05a3bd915708",
          "sha256": "c020aa3f4ea0cce204dd633a70cad7cb745178bb08634dce0cb5c5fc05c255a6",
          "sha1": "965719663fd80fb683a062882c3d869bb8b99d2c",
          "md5": "35bcf21a1fcef4eda9904e95e1bca048"
        }
      ]
    }
  ]
}
