{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22335,
          "sha512": "04a261f3847c7489d18c6b62fa5fea8bb88ddfd12044d102ebbdb2bc4facbf58cc062bb3fe0f940f1e41a9f40ad7853ba1a8278d6c91c417bc842f1fccca0615",
          "sha256": "b3224c58d6ae98a5c5e1edb80c176afe2ddb670978675ddca373e0d80bad4fcb",
          "sha1": "2b4d829f9f8a29c23d9b1becc089e67ea8115185",
          "md5": "4fde51fba3575b68b3c1ec319148f313"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22335,
          "sha512": "04a261f3847c7489d18c6b62fa5fea8bb88ddfd12044d102ebbdb2bc4facbf58cc062bb3fe0f940f1e41a9f40ad7853ba1a8278d6c91c417bc842f1fccca0615",
          "sha256": "b3224c58d6ae98a5c5e1edb80c176afe2ddb670978675ddca373e0d80bad4fcb",
          "sha1": "2b4d829f9f8a29c23d9b1becc089e67ea8115185",
          "md5": "4fde51fba3575b68b3c1ec319148f313"
        }
      ]
    }
  ]
}
