{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "sentry_flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry_flutter_release-1.0.aar",
          "url": "sentry_flutter_release-1.0.aar",
          "size": 62171,
          "sha512": "8150c0867d27392564c7422c270126f29dcd9596e36fa4bbf46ba996d2505873cd9b95bf7bc2e81723342c586da0544c51c9a3570009224e20959a41e9a2c3c6",
          "sha256": "5973963ce4750348b5d0f3ced8c9b484e118113179184f0c619ee3a5b0236db4",
          "sha1": "c6453134621bdde88c8eef661c1f26c88cf3cdcf",
          "md5": "719eb478fe12ea0e43f337f668d5a0de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry_flutter_release-1.0.aar",
          "url": "sentry_flutter_release-1.0.aar",
          "size": 62171,
          "sha512": "8150c0867d27392564c7422c270126f29dcd9596e36fa4bbf46ba996d2505873cd9b95bf7bc2e81723342c586da0544c51c9a3570009224e20959a41e9a2c3c6",
          "sha256": "5973963ce4750348b5d0f3ced8c9b484e118113179184f0c619ee3a5b0236db4",
          "sha1": "c6453134621bdde88c8eef661c1f26c88cf3cdcf",
          "md5": "719eb478fe12ea0e43f337f668d5a0de"
        }
      ]
    }
  ]
}
