{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 39684,
          "sha512": "74b88091dd04e8ab9feba7b5cb78b008960a2016d1795a333d44ec338cead88e919803b84ff2addbd9ac4779d86db9b96f0aea2fa436d4fd6b7d1ca85f21075a",
          "sha256": "ed643e32121e865f838abf0806079652a4b309e7dd50d58ec498fe35ffa420a7",
          "sha1": "7c71dfba653b8ce75404f7b8577390f986736798",
          "md5": "8c389586932feb98057cdf1fce61702e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.7"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 39684,
          "sha512": "74b88091dd04e8ab9feba7b5cb78b008960a2016d1795a333d44ec338cead88e919803b84ff2addbd9ac4779d86db9b96f0aea2fa436d4fd6b7d1ca85f21075a",
          "sha256": "ed643e32121e865f838abf0806079652a4b309e7dd50d58ec498fe35ffa420a7",
          "sha1": "7c71dfba653b8ce75404f7b8577390f986736798",
          "md5": "8c389586932feb98057cdf1fce61702e"
        }
      ]
    }
  ]
}
