{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.photo_manager",
    "module": "photo_manager_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_release-1.0.aar",
          "url": "photo_manager_release-1.0.aar",
          "size": 191701,
          "sha512": "480e4d90a9e60cc8326c6d7e8dd25bd0b4d54e2571cbe93741cec78615ae39580d4529b577f66ad76f52f9b302229e65498678cacc9ce19847d329d1b9b0ca28",
          "sha256": "c54b0dd8361bd04761456053b6c24be99c792ad7e743cfe5e831cef2de381075",
          "sha1": "ae8e8533ec251656b3c70079d5a1b9b26ba315fa",
          "md5": "35592af827caa59824e25506f0485d36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_release-1.0.aar",
          "url": "photo_manager_release-1.0.aar",
          "size": 191701,
          "sha512": "480e4d90a9e60cc8326c6d7e8dd25bd0b4d54e2571cbe93741cec78615ae39580d4529b577f66ad76f52f9b302229e65498678cacc9ce19847d329d1b9b0ca28",
          "sha256": "c54b0dd8361bd04761456053b6c24be99c792ad7e743cfe5e831cef2de381075",
          "sha1": "ae8e8533ec251656b3c70079d5a1b9b26ba315fa",
          "md5": "35592af827caa59824e25506f0485d36"
        }
      ]
    }
  ]
}
