{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.photo_manager",
    "module": "photo_manager_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_profile-1.0.aar",
          "url": "photo_manager_profile-1.0.aar",
          "size": 191701,
          "sha512": "c595c77a903087ec9d96655ef310133fb528ef1af29f339aa43d2965f2680f511b709e82e5a68bafead87c1a444bb9a72675ea8c0590ec1f8a2859340c9eb590",
          "sha256": "b1433de98976afe99c5a8ce366150d5217240e8665c9e232d302f5262a459cf4",
          "sha1": "12ff72b953eac409e2dcfcf9a303872a7bd702bf",
          "md5": "fdda5bb7264fca4cb637423aff6359e7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_profile-1.0.aar",
          "url": "photo_manager_profile-1.0.aar",
          "size": 191701,
          "sha512": "c595c77a903087ec9d96655ef310133fb528ef1af29f339aa43d2965f2680f511b709e82e5a68bafead87c1a444bb9a72675ea8c0590ec1f8a2859340c9eb590",
          "sha256": "b1433de98976afe99c5a8ce366150d5217240e8665c9e232d302f5262a459cf4",
          "sha1": "12ff72b953eac409e2dcfcf9a303872a7bd702bf",
          "md5": "fdda5bb7264fca4cb637423aff6359e7"
        }
      ]
    }
  ]
}
