{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "sentry_flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry_flutter_profile-1.0.aar",
          "url": "sentry_flutter_profile-1.0.aar",
          "size": 61906,
          "sha512": "12fd9cbaa45b84c0db86fb780714c461dce9e8e5ca45d6e5eb17dd8a0131bd1728d654906fea52fbc6b43d33fad9b34999b5d8b07ad80e26e23e0c18f915f15e",
          "sha256": "a651f9574d65dc3c291557b440453a522874511399f530932fd00936f85d1886",
          "sha1": "1ceac1c4711864c8a54625f2405632b4ed8a3172",
          "md5": "cf312078d8d2f19a33e4cc503409767d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry_flutter_profile-1.0.aar",
          "url": "sentry_flutter_profile-1.0.aar",
          "size": 61906,
          "sha512": "12fd9cbaa45b84c0db86fb780714c461dce9e8e5ca45d6e5eb17dd8a0131bd1728d654906fea52fbc6b43d33fad9b34999b5d8b07ad80e26e23e0c18f915f15e",
          "sha256": "a651f9574d65dc3c291557b440453a522874511399f530932fd00936f85d1886",
          "sha1": "1ceac1c4711864c8a54625f2405632b4ed8a3172",
          "md5": "cf312078d8d2f19a33e4cc503409767d"
        }
      ]
    }
  ]
}
