{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 23081,
          "sha512": "d19c0cc1cf044c61eac4ffb9ffa74efa0b53e08c8840f8ae8b5a140358d49f8a0a53dd2a598658d64f6c286e068bd2877ddb75f95d46cb4b9221617d93c02547",
          "sha256": "cb5598f56b76f8dd32b4e33b259748182350b2f3d64593df3971caede8240c9f",
          "sha1": "f30d4db683675ed2cdb6eea4e9ac1ec59754f7e0",
          "md5": "fe4de8e2bb15405af7e26065d027ffb4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 23081,
          "sha512": "d19c0cc1cf044c61eac4ffb9ffa74efa0b53e08c8840f8ae8b5a140358d49f8a0a53dd2a598658d64f6c286e068bd2877ddb75f95d46cb4b9221617d93c02547",
          "sha256": "cb5598f56b76f8dd32b4e33b259748182350b2f3d64593df3971caede8240c9f",
          "sha1": "f30d4db683675ed2cdb6eea4e9ac1ec59754f7e0",
          "md5": "fe4de8e2bb15405af7e26065d027ffb4"
        }
      ]
    }
  ]
}
