{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "sentry_flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry_flutter_debug-1.0.aar",
          "url": "sentry_flutter_debug-1.0.aar",
          "size": 64403,
          "sha512": "7250a355507c608da47af13d5d839239edeebec36d2ea5db8824e0b854dd1eea309268fc3cf56119d25f236abedfa3277c9934c2581866989eb82595951955aa",
          "sha256": "9d7c5998b7be8f6dab1b1c501fdf180260e7890d21019244d6e616bf8438caf1",
          "sha1": "f244dea7cf1e5aba6116dd15f41f396b5f90a302",
          "md5": "453d1eead01e76d2ffdfbc5c4ca308ee"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry_flutter_debug-1.0.aar",
          "url": "sentry_flutter_debug-1.0.aar",
          "size": 64403,
          "sha512": "7250a355507c608da47af13d5d839239edeebec36d2ea5db8824e0b854dd1eea309268fc3cf56119d25f236abedfa3277c9934c2581866989eb82595951955aa",
          "sha256": "9d7c5998b7be8f6dab1b1c501fdf180260e7890d21019244d6e616bf8438caf1",
          "sha1": "f244dea7cf1e5aba6116dd15f41f396b5f90a302",
          "md5": "453d1eead01e76d2ffdfbc5c4ca308ee"
        }
      ]
    }
  ]
}
