{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_profile-1.0.aar",
          "url": "package_info_plus_profile-1.0.aar",
          "size": 7918,
          "sha512": "db35f272d4316d5fd726787810c0f827e2a438ba8f1ffab9a378de4e8279ca131b28d1108a4ac631c89c083bce3c75b3215fd1c9823ecf6c90e9357736bd325f",
          "sha256": "7d80afa692c960f31d1352d5dee91efb77360c9ee761cc4b3c157188a72883ba",
          "sha1": "74f137a238da36e301dc7c549a00988fc0870271",
          "md5": "39e0b2e4e46dfc591f8f44403574c421"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_profile-1.0.aar",
          "url": "package_info_plus_profile-1.0.aar",
          "size": 7918,
          "sha512": "db35f272d4316d5fd726787810c0f827e2a438ba8f1ffab9a378de4e8279ca131b28d1108a4ac631c89c083bce3c75b3215fd1c9823ecf6c90e9357736bd325f",
          "sha256": "7d80afa692c960f31d1352d5dee91efb77360c9ee761cc4b3c157188a72883ba",
          "sha1": "74f137a238da36e301dc7c549a00988fc0870271",
          "md5": "39e0b2e4e46dfc591f8f44403574c421"
        }
      ]
    }
  ]
}
