{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kryptogo.kg_sdk",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "de.gigadroid.flutterudid",
          "module": "flutter_udid_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.chavesgu.scan",
          "module": "scan_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "android_generated",
          "module": "sentry_flutter_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.fluttercandies.photo_manager",
          "module": "photo_manager_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 27268854,
          "sha512": "29077fcd2e47e0fcdff4f8710c486b4ee6a448adfc5f0ef369818c895ff540d9c32c8ad95497080fe55430c698abf69f844acf1f75c65db98b78bf7c36d270bc",
          "sha256": "8943710c5d73c183130b80c7f8c3aba49a4cfd9e59034856b484442bdee4a898",
          "sha1": "82c946f2d455a97b263551e2311302f363cbd823",
          "md5": "67c317fd27e23c6155fc6ec9fbd3ebc5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "de.gigadroid.flutterudid",
          "module": "flutter_udid_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.chavesgu.scan",
          "module": "scan_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.touchcapture.qr.flutterqr",
          "module": "qr_code_scanner_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "android_generated",
          "module": "sentry_flutter_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.fluttercandies.photo_manager",
          "module": "photo_manager_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 27268854,
          "sha512": "29077fcd2e47e0fcdff4f8710c486b4ee6a448adfc5f0ef369818c895ff540d9c32c8ad95497080fe55430c698abf69f844acf1f75c65db98b78bf7c36d270bc",
          "sha256": "8943710c5d73c183130b80c7f8c3aba49a4cfd9e59034856b484442bdee4a898",
          "sha1": "82c946f2d455a97b263551e2311302f363cbd823",
          "md5": "67c317fd27e23c6155fc6ec9fbd3ebc5"
        }
      ]
    }
  ]
}
