{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7922,
          "sha512": "df1e4a1efdc3cda795953098496cca5c6097a081df020626880e7708310f79d0afd2ce3ffde75873e116745725e54b5a202fdd4744bd793af9a040dfd68b7cc5",
          "sha256": "1251aca5552d839b55c09e102394d02cfc69691009e0e803c615ad226dac0150",
          "sha1": "995014f989a114116286d2551a2883a3f554bdb1",
          "md5": "e590fb7fccfbebefe3862973c3a11abf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7922,
          "sha512": "df1e4a1efdc3cda795953098496cca5c6097a081df020626880e7708310f79d0afd2ce3ffde75873e116745725e54b5a202fdd4744bd793af9a040dfd68b7cc5",
          "sha256": "1251aca5552d839b55c09e102394d02cfc69691009e0e803c615ad226dac0150",
          "sha1": "995014f989a114116286d2551a2883a3f554bdb1",
          "md5": "e590fb7fccfbebefe3862973c3a11abf"
        }
      ]
    }
  ]
}
